server.port: ${PORT:9999}

spring.application.name: api-gateway

eureka.port: ${EUREKA_PORT:8761}
eureka.hostname: ${EUREKA_HOSTNAME:localhost}

eureka.client.serviceUrl.defaultZone: http://${eureka.hostname}:${eureka.port}/eureka/
eureka.client.registerWithEureka: true

zuul:
    prefix: /assignment
    routes:
        product-service:
            path: /product/**
            serviceId: product-service
        cart-service:
            path: /cart/**
            serviceId: cart-service
        discount-service:
            path: /discount/**
            serviceId: discount-service
        delivery-service:
            path: /delivery/**
            serviceId: delivery-service