version: '3.1'
services:
  api-gateway:
    image: docker.pkg.github.com/betulcetinkaya/api-gateway/${IMAGE_NAME}:${TAG}
    container_name: api-gateway
    env_file: docker-compose.env
    ports:
      - 80:80
    networks:
        - services
networks:
  services:
    external:
      name: services
