version: '3.1'
services:
  api-gateway:
    image: betulcetinkaya/api-gateway:${TAG}
    container_name: api-gateway
    env_file: docker-compose.env
    ports:
      - 8080:8080
    networks:
        - services
networks:
  services:
    external:
      name: services
